# Generated by Django 4.0.2 on 2022-03-16 06:41

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('big_cheese', '0002_pickuplocation_description'),
        ('checkout', '0002_remove_order_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='pickup_location',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='big_cheese.pickuplocation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='big_cheese.pickuplocation'),
        ),
    ]
