# Generated by Django 4.0.2 on 2022-03-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_country_orderlineitem_pickup_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='grand_total',
        ),
    ]
